### ISSUE TITLE
m17-coder-sym omits first 16 bytes of payload

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/M17_Implementations#32]
Probably something wrong with how `fread()` functions are called.

**Comment by sp5wwp** [comment]
@argilo @maitbot can you confirm?

**Comment by jmfriedt** [comment]
I have always wondered why https://github.com/M17-Project/M17_Implementations/blob/32b63ff74eb554392e85c5caf700d400006a616d/SP5WWP/m17-coder/m17-coder-sym.c#L139-L143 outside the infinite loop (including ``if(fread(next_data, 16, 1, stdin)<1) finished=1;``) followed by https://github.com/M17-Project/M17_Implementations/blob/32b63ff74eb554392e85c5caf700d400006a616d/SP5WWP/m17-coder/m17-coder-sym.c#L171-L176 which, as commented ``//we could discard the data we already have``, means the 16 bytes read earlier are lost. In ``gr-m17`` I got rid of ll.139-143 since the fields are filled from the GRC block and not from stdin.

**Comment by sp5wwp** [comment]
I believe I have fixed it for good with [1538db6](https://github.com/M17-Project/M17_Implementations/commit/1538db6043a3caeaa01a8faca2e0656b75076fd3).
